name = "leanfmt"
version = "0.1.0"
description = "A structure-preserving code formatter for Lean"
keywords = ["lean4", "formatter", "devtool", "development-tools"]
defaultTargets = ["LeanFmt", "fmt"]
testDriver = "LeanFmt.Tests"
lintDriver = "runLinter"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.32.0"

[[lean_lib]]
name = "LeanFmt"

[[lean_lib]]
name = "LeanFmt.Tests"
roots = ["LeanFmt.Tests.Suite"]

[[lean_exe]]
name = "fmt"
root = "LeanFmt.Cli"
supportInterpreter = true

[[lean_exe]]
name = "fmt-test"
root = "LeanFmt.Tests.Main"

[[lean_exe]]
name = "runLinter"
srcDir = "scripts"
supportInterpreter = true
