name = "leanfmt"
version = "0.2.2"
description = "A structure-preserving code formatter for Lean"
keywords = ["lean4", "formatter", "devtool", "development-tools"]
license = "MIT"
defaultTargets = ["LeanFmt", "fmt"]
testDriver = "LeanFmt.Tests"

[[lean_lib]]
name = "LeanFmt"

[[lean_lib]]
name = "LeanFmt.Tests"
roots = ["LeanFmt.Tests.Suite"]

[[lean_exe]]
name = "fmt"
root = "LeanFmt.Cli"
supportInterpreter = true

[[lean_exe]]
name = "fmt-test"
root = "LeanFmt.Tests.Main"
supportInterpreter = true
